global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sentiment-ai'
    metrics_path: /metrics
    static_configs:
      - targets: ['sentiment-ai:8000']
        labels:
          app: 'sentiment-ai'
